export const AWS_COGNITO_MODULE_OPTIONS = Symbol('AWS_COGNITO_MODULE_OPTIONS');
export const AWS_COGNITO_CLIENT = Symbol('AWS_COGNITO_CLIENT');
export const AWS_COGNITO_IDENTITY_TOKEN_DURATION = 3600; // 1 hour
