import { Module } from '@nestjs/common';
import {
  AdminFCMTokenMongooseModule,
  AdminMongooseModule,
  AdminNotificationMongooseModule,
  AdminRolesMongooseModule,
  AppVersionsMongooseModule,
  AreaMongooseModule,
  ChatMessageMongooseModule,
  ChatRoomMongooseModule,
  CityMongooseModule,
  CommentMongooseModule,
  CommentReplyMongooseModule,
  CommonModule,
  CountryMongooseModule,
  DynamicLinkMongooseModule,
  EventCategoryMongooseModule,
  EventFacilityMongooseModule,
  EventMongooseModule,
  EventRsvpMongooseModule,
  LikeMongooseModule,
  LostFoundMongooseModule,
  PendingPetFollowMongooseModule,
  PendingUserFollowMongooseModule,
  PendingUserMongooseModule,
  PetBreedMongooseModule,
  PetFollowMongooseModule,
  PetMatchMongooseModule,
  PetMongooseModule,
  PetTypeMongooseModule,
  PostMongooseModule,
  ReportMongooseModule,
  UserAddressMongooseModule,
  UserBlockMongooseModule,
  UserChatRoomRelationMongooseModule,
  UserFCMTokenMongooseModule,
  UserFollowMongooseModule,
  UserMessageStatusMongooseModule,
  UserMongooseModule,
  UserNotificationMongooseModule,
  UserPushNotificationMongooseModule,
  UserSegmentMongooseModule,
} from '@instapets-backend/common';

const imports = [
  AdminMongooseModule,
  AdminFCMTokenMongooseModule,
  AdminRolesMongooseModule,
  AppVersionsMongooseModule,
  AreaMongooseModule,
  ChatMessageMongooseModule,
  ChatRoomMongooseModule,
  UserChatRoomRelationMongooseModule,
  UserMessageStatusMongooseModule,
  CityMongooseModule,
  CountryMongooseModule,
  CommentMongooseModule,
  CommentReplyMongooseModule,
  LikeMongooseModule,
  ReportMongooseModule,
  EventCategoryMongooseModule,
  EventFacilityMongooseModule,
  EventRsvpMongooseModule,
  EventMongooseModule,
  LostFoundMongooseModule,
  DynamicLinkMongooseModule,
  UserPushNotificationMongooseModule,
  UserSegmentMongooseModule,
  PetMatchMongooseModule,
  AdminNotificationMongooseModule,
  PendingPetFollowMongooseModule,
  PetBreedMongooseModule,
  PetTypeMongooseModule,
  PetFollowMongooseModule,
  PetMongooseModule,
  PostMongooseModule,
  PendingUserMongooseModule,
  PendingUserFollowMongooseModule,
  UserAddressMongooseModule,
  UserBlockMongooseModule,
  UserFCMTokenMongooseModule,
  UserFollowMongooseModule,
  UserMongooseModule,
  UserNotificationMongooseModule,
];
const providers = [];

@Module({
  imports,
  providers,
  exports: [...imports, ...providers],
})
export class SharedModule {}
