export enum UploadModelResources {
  POSTS = 'posts',
  LOST_POSTS = 'lost-posts',
  FOUND_POSTS = 'found-posts',
  EVENTS = 'events',
  USER_PROFILE_PICTURE = 'user-profile-picture',
  PET_PROFILE_PICTURE = 'pet-profile-picture',
  CHAT_MESSAGE_MEDIA = 'chat-message-media',
  GROUP_CHAT_ROOM_PICTURE = 'group-chat-room-picture',
  DYNAMIC_LINK_MEDIA = 'dynamic-link-media',
  USER_PUSH_NOTIFICATION_MEDIA = 'user-push-notification-media',
  TOPIC_MEDIA = 'topic-media',
  BRANDS = 'brands',
  BRANCHES = 'branches',
  STAFF_MEMBERS_DOCUMENTS = 'staff-member-documents',
  PRODUCT_CATEGORY_ICON = 'product-category-icon',
  PRODUCT_SUBCATEGORY_ICON = 'product-subcategory-icon',
}
