export const NEO4J_MODULE_OPTIONS = Symbol('NEO4J_MODULE_OPTIONS');

export const NEO4J_MODULE_MERGED_OPTIONS = Symbol('NEO4J_MODULE_MERGED_OPTIONS');

export const NEO4J_DRIVER = Symbol('NEO4J_DRIVER');
