export enum StripeMetadataEventsEnum {
  SETUP_INTENT_SUCCEEDED = 'SETUP_INTENT_SUCCEEDED',
  ORDER_PAYMENT_INTENT_PREPARED_FOR_MANUAL_CAPTURE = 'ORDER_PAYMENT_INTENT_PREPARED_FOR_MANUAL_CAPTURE',
  ORDER_SUBSCRIPTION_DROP_OFF_PAYMENT_INTENT_PREPARED_FOR_MANUAL_CAPTURE = 'ORDER_SUBSCRIPTION_DROP_OFF_PAYMENT_INTENT_PREPARED_FOR_MANUAL_CAPTURE',
  ORDER_SUBSCRIPTION_PAYMENT_CREATED = 'ORDER_SUBSCRIPTION_PAYMENT_CREATED',
}
