import { AppConfigOptions } from '@common/interfaces/app-config-options';
import { IProcessEnv } from '@common/interfaces/env';
import Joi from 'joi';

export const baseConfigObject = {
  NODE_ENV: Joi.string().valid('loc', 'dev', 'tst', 'prod').required(),
  MONGODB_URL: Joi.string().required(),
  USER_JWT_SECRET: Joi.string().required(),
  USER_JWT_REFRESH_SECRET: Joi.string().required(),
  USER_JWT_EXPIRY: Joi.number().required(),
  USER_JWT_REFRESH_EXPIRY: Joi.string().required(),
  CUSTOMER_JWT_SECRET: Joi.string().required(),
  CUSTOMER_JWT_REFRESH_SECRET: Joi.string().required(),
  CUSTOMER_JWT_EXPIRY: Joi.number().required(),
  CUSTOMER_JWT_REFRESH_EXPIRY: Joi.string().required(),
  ADMIN_JWT_SECRET: Joi.string().required(),
  ADMIN_JWT_REFRESH_SECRET: Joi.string().required(),
  ADMIN_JWT_EXPIRY: Joi.number().required(),
  ADMIN_JWT_REFRESH_EXPIRY: Joi.string().required(),
  S2S_JWT_SECRET: Joi.string().required(),
  NEO4J_DB_URL: Joi.string().required(),
  NEO4J_USER: Joi.string().required(),
  NEO4J_PASSWORD: Joi.string().required(),
  REDIS_HOST: Joi.string().optional().default('localhost'),
  REDIS_PORT: Joi.number().optional().default(6379),
  RABBIT_URI: Joi.string().required(),
  LOGDNA_KEY: Joi.string().required(),
  AWS_UPLOAD_BUCKET_NAME: Joi.string().required(),
  AWS_TEMP_UPLOAD_BUCKET_NAME: Joi.string().required(),
  AWS_UPLOAD_ACCESS_KEY_ID: Joi.string().required(),
  AWS_UPLOAD_SECRET_ACCESS_KEY: Joi.string().required(),
  AWS_UPLOAD_REGION: Joi.string().required(),
  MEDIA_DOMAIN: Joi.string().required(),
  AWS_SES_ACCESS_KEY_ID: Joi.string().required(),
  AWS_SES_SECRET_ACCESS_KEY: Joi.string().required(),
  AWS_SES_REGION: Joi.string().required(),
  AWS_SNS_VIDEO_ANALYSIS_TOPIC_ARN: Joi.string().required(),
  AWS_REKOGNITION_ACCESS_KEY_ID: Joi.string().required(),
  AWS_REKOGNITION_SECRET_ACCESS_KEY: Joi.string().required(),
  AWS_REKOGNITION_REGION: Joi.string().required(),
  AWS_REKOGNITION_JOB_ROLE_ARN: Joi.string().required(),
  AWS_COGNITO_ACCESS_KEY_ID: Joi.string().required(),
  AWS_COGNITO_SECRET_ACCESS_KEY: Joi.string().required(),
  AWS_COGNITO_REGION: Joi.string().required(),
  AWS_COGNITO_IDENTITY_POOL_ID: Joi.string().required(),
  AWS_COGNITO_DEVELOPER_IDENTITY_ID: Joi.string().required(),
  AWS_SCHEDULER_ACCESS_KEY_ID: Joi.string().required(),
  AWS_SCHEDULER_SECRET_ACCESS_KEY: Joi.string().required(),
  AWS_SCHEDULER_REGION: Joi.string().required(),
  AWS_SCHEDULER_LAMBDA_PUSH_NOTIFICATIONS_ARN: Joi.string().required(),
  AWS_SCHEDULER_SERVICE_ROLE_ARN: Joi.string().required(),
  AWS_LAMBDA_ACCESS_KEY_ID: Joi.string().required(),
  AWS_LAMBDA_SECRET_ACCESS_KEY: Joi.string().required(),
  AWS_LAMBDA_REGION: Joi.string().required(),
  AWS_LAMBDA_MEDIA_MODERATION_FUNCTION_NAME: Joi.string().required(),
  ADMIN_GOOGLE_CLIENT_ID: Joi.string().required(),
  ADMIN_GOOGLE_SECRET: Joi.string().required(),
  USER_GOOGLE_CLIENT_ID: Joi.string().required(),
  USER_GOOGLE_SECRET: Joi.string().required(),
  USER_APPLE_CLIENT_ID: Joi.string().required(),
  CUSTOMER_GOOGLE_CLIENT_ID: Joi.string().required(),
  CUSTOMER_GOOGLE_SECRET: Joi.string().required(),
  CUSTOMER_APPLE_CLIENT_ID: Joi.string().required(),
  ELASTIC_SEARCH_URL: Joi.string().required(),
  FIREBASE_USER_API_KEY: Joi.string().required(),
  FIREBASE_USER_DYNAMIC_LINKS_DOMAIN: Joi.string().required(),
  FIREBASE_USER_DEEP_LINKS_DOMAIN: Joi.string().required(),
  FIREBASE_USER_DEFAULT_DYNAMIC_LINK: Joi.string().required(),
  FIREBASE_USER_DEFAULT_DEEP_LINK: Joi.string().required(),
  FIREBASE_ADMIN_DEFAULT_DEEP_LINK: Joi.string().required(),
  FIREBASE_ADMIN_DEEP_LINKS_DOMAIN: Joi.string().required(),
  USER_APP_NAME: Joi.string().required(),
  USER_APP_DESCRIPTION: Joi.string().required(),
  USER_APP_LOGO: Joi.string().required(),
  USER_APP_ANDROID_PACKAGE_NAME: Joi.string().required(),
  USER_APP_IOS_PACKAGE_NAME: Joi.string().required(),
  CLINICS_RESET_PASSWORD_PATH: Joi.string().required(),
  CLINICS_DOMAIN: Joi.string().required(),
  CLINICS_EMAIL_VERIFICATION_PATH: Joi.string().required(),
  CLINIC_JWT_SECRET: Joi.string().required(),
  CLINIC_JWT_REFRESH_SECRET: Joi.string().required(),
  CLINIC_JWT_EXPIRY: Joi.number().required(),
  CLINIC_JWT_REFRESH_EXPIRY: Joi.string().required(),
  USER_MAPS_API_KEY: Joi.string().required(),
  FIREBASE_SERVICE_PROVIDER_DEFAULT_DEEP_LINK: Joi.string().required(),
  FIREBASE_SERVICE_PROVIDER_DEEP_LINKS_DOMAIN: Joi.string().required(),
  STRIPE_WEBHOOK_SECRET: Joi.string().required(),
  STRIPE_SECRET_KEY: Joi.string().required(),
} satisfies Record<keyof IProcessEnv, any>;

export const configSchema = (appConfig: AppConfigOptions) => {
  return Joi.object({
    ...baseConfigObject,
    APP_SHORT_NAME: Joi.string().default(appConfig.appShortName),
  });
};
