import { Module } from '@nestjs/common';
import { SharedModule } from '@graphsync/shared-module/shared.module';
import {
  CityListenerService,
  CitySynchronizerService,
  CommentLikeListenerService,
  CommentLikeSynchronizerService,
  CommentListenerService,
  CommentReplyLikeListenerService,
  CommentReplyLikeSynchronizerService,
  CommentReplyListenerService,
  CommentReplySynchronizerService,
  CommentSynchronizerService,
  CountryListenerService,
  CountrySynchronizerService,
  PetFollowListenerService,
  PetFollowSynchronizerService,
  PetListenerService,
  PetMatchListenerService,
  PetMatchSynchronizerService,
  PetSynchronizerService,
  PostLikeListenerService,
  PostLikeSynchronizerService,
  PostListenerService,
  PostSynchronizerService,
  TopicListenerService,
  TopicSynchronizerService,
  UserFollowListenerService,
  UserFollowSynchronizerService,
  UserHasInterestSynchronizerService,
  UserListenerService,
  UserSynchronizerService,
  UserTopicListenerService,
} from './sync';
import { MaintainUserInteractionsService } from './shared';

@Module({
  imports: [SharedModule],
  controllers: [],
  providers: [
    CityListenerService,
    CitySynchronizerService,
    CommentLikeListenerService,
    CommentLikeSynchronizerService,
    CommentListenerService,
    CommentReplyLikeListenerService,
    CommentReplyLikeSynchronizerService,
    CommentReplyListenerService,
    CommentReplySynchronizerService,
    CommentSynchronizerService,
    CountryListenerService,
    CountrySynchronizerService,
    TopicListenerService,
    TopicSynchronizerService,
    PetFollowListenerService,
    PetFollowSynchronizerService,
    PetListenerService,
    PetSynchronizerService,
    PostLikeListenerService,
    PostLikeSynchronizerService,
    PostListenerService,
    PostSynchronizerService,
    UserFollowListenerService,
    UserFollowSynchronizerService,
    UserListenerService,
    UserTopicListenerService,
    UserSynchronizerService,
    MaintainUserInteractionsService,
    PetMatchSynchronizerService,
    PetMatchListenerService,
    UserHasInterestSynchronizerService,
  ],
})
export class UserModule {}
