export enum PetMatchStatusEnum {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
}

export enum PetMatchEventsEnum {
  SEND_ACCEPTED_NOTIFICATION = 'SEND_ACCEPTED_NOTIFICATION',
  SEND_REQUESTED_NOTIFICATION = 'SEND_REQUESTED_NOTIFICATION',
}
