export const FCM_MODULE_OPTIONS = Symbol('FCM_MODULE_OPTIONS');

export const FCM_MODULE_MERGED_OPTIONS = Symbol('FCM_MODULE_MERGED_OPTIONS');

export const FCM_USER_APP = Symbol('FCM_USER_APP');
export const FCM_ADMIN_APP = Symbol('FCM_ADMIN_APP');
export const FCM_SERVICE_PROVIDER_APP = Symbol('FCM_SERVICE_PROVIDER_APP');
