export enum UserNotificationTypeEnum {
  POST_LIKE = 'POST_LIKE',
  POST_COMMENT = 'POST_COMMENT',

  COMMENT_LIKE = 'COMMENT_LIKE',
  COMMENT_REPLY = 'COMMENT_REPLY',

  COMMENT_REPLY_LIKE = 'COMMENT_REPLY_LIKE',

  USER_FOLLOW = 'USER_FOLLOW',
  PENDING_USER_FOLLOW = 'PENDING_USER_FOLLOW',
  PET_FOLLOW = 'PET_FOLLOW',
  PENDING_PET_FOLLOW = 'PENDING_PET_FOLLOW',

  PET_MATCH_ACCEPT = 'PET_MATCH_ACCEPT',
  PET_MATCH_REQUEST = 'PET_MATCH_REQUEST',

  CHAT_MESSAGE = 'CHAT_MESSAGE',
  CHAT_REQUEST = 'CHAT_REQUEST',

  USER_TAG = 'USER_TAG',
  PET_TAG = 'PET_TAG',

  EVENT_UPDATE = 'EVENT_UPDATE',
  EVENT_CANCEL = 'EVENT_CANCEL',

  MARKETING = 'MARKETING',

  APPOINTMENT = 'APPOINTMENT',
}
